ARG NODE_VERSION=24
ARG BASE_OS_VERSION=bookworm
ARG BASE_IMAGE_TYPE=slim
ARG SERVER_PORT=3001

FROM node:${NODE_VERSION}-${BASE_OS_VERSION}-${BASE_IMAGE_TYPE} AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server


FROM node:${NODE_VERSION}-${BASE_OS_VERSION}-${BASE_IMAGE_TYPE} AS production
WORKDIR /app

COPY --from=builder /app/packages/server/dist/ /app/
COPY --from=builder /app/packages/server/package.json /app/package.json
RUN yarn install --production=true

EXPOSE $SERVER_PORT
CMD [ "node", "/app/index.js" ]
