ARG NODE_VERSION=22.20
ARG BASE_OS_VERSION=bookworm
ARG BASE_IMAGE_TYPE=slim
ARG CLIENT_PORT=3001

FROM node:${NODE_VERSION}-${BASE_OS_VERSION}-${BASE_IMAGE_TYPE} AS builder

WORKDIR /app

COPY package.json yarn.lock lerna.json ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client


FROM nginx:1.29.1-alpine-slim AS production
WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/
COPY --from=builder /app/packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
