name: Branch Protection Setup

on:
  workflow_dispatch:
  schedule:
    # Запускается каждый день в 2:00 UTC для проверки настроек
    - cron: '0 2 * * *'

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const protectedBranches = ['main', 'dev'];
            
            for (const branch of protectedBranches) {
              const branchExists = branches.some(b => b.name === branch);
              
              if (branchExists) {
                try {
                  await github.rest.repos.updateBranchProtection({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    branch: branch,
                    required_status_checks: {
                      strict: true,
                      contexts: ['Lint', 'Test']
                    },
                    enforce_admins: false,
                    required_pull_request_reviews: {
                      required_approving_review_count: 2,
                      dismiss_stale_reviews: true,
                      require_code_owner_reviews: false,
                      require_last_push_approval: true
                    },
                    restrictions: null,
                    allow_force_pushes: false,
                    allow_deletions: false,
                    block_creations: false,
                    required_conversation_resolution: true
                  });
                  
                  console.log(`✅ Branch protection updated for ${branch}`);
                } catch (error) {
                  console.log(`❌ Failed to update branch protection for ${branch}:`, error.message);
                }
              } else {
                console.log(`⚠️ Branch ${branch} does not exist, skipping protection setup`);
              }
            }

      - name: Create Pull Request Template
        uses: actions/github-script@v7
        with:
          script: |
            const templateContent = [
              '## Описание изменений',
              '',
              'Опишите кратко что было изменено в этом PR.',
              '',
              '## Тип изменений',
              '',
              '- [ ] 🐛 Исправление бага',
              '- [ ] ✨ Новая функциональность',
              '- [ ] 📝 Документация',
              '- [ ] 🎨 Улучшение UI/UX',
              '- [ ] ⚡️ Производительность',
              '- [ ] 🔧 Рефакторинг',
              '- [ ] 🧪 Тесты',
              '- [ ] 📦 Зависимости',
              '',
              '## Чек-лист',
              '',
              '- [ ] Код соответствует кодстайлу проекта',
              '- [ ] Добавлены/обновлены тесты',
              '- [ ] Документация обновлена',
              '- [ ] Изменения протестированы локально',
              '- [ ] Все CI проверки прошли успешно',
              '',
              '## Дополнительная информация',
              '',
              'Добавьте любую дополнительную информацию, которая может быть полезна для ревьюеров.',
              '',
              '---',
              '',
              '**Создано с ❤️ используя Feature-Sliced Design**'
            ].join('\n');

            try {
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: '.github/pull_request_template.md',
                message: 'Add pull request template',
                content: Buffer.from(templateContent).toString('base64'),
                branch: 'main'
              });
              
              console.log('✅ Pull request template created');
            } catch (error) {
              console.log('❌ Failed to create pull request template:', error.message);
            }

      - name: Create Issue Templates
        uses: actions/github-script@v7
        with:
          script: |
            const bugReportTemplate = [
              '---',
              'name: 🐛 Bug Report',
              'about: Создать отчет об ошибке',
              'title: \'[BUG] \'',
              'labels: [\'bug\']',
              'assignees: \'\'',
              '---',
              '',
              '## Описание бага',
              '',
              'Краткое и четкое описание бага.',
              '',
              '## Шаги для воспроизведения',
              '',
              '1. Перейти к \'...\'',
              '2. Нажать на \'....\'',
              '3. Прокрутить до \'....\'',
              '4. Увидеть ошибку',
              '',
              '## Ожидаемое поведение',
              '',
              'Краткое и четкое описание того, что должно было произойти.',
              '',
              '## Скриншоты',
              '',
              'Если применимо, добавьте скриншоты для объяснения проблемы.',
              '',
              '## Окружение',
              '',
              ' - OS: [например Windows 10]',
              ' - Browser: [например chrome, safari]',
              ' - Version: [например 22]',
              '',
              '## Дополнительная информация',
              '',
              'Добавьте любую другую информацию о проблеме здесь.'
            ].join('\n');

            const featureRequestTemplate = [
              '---',
              'name: ✨ Feature Request',
              'about: Предложить идею для проекта',
              'title: \'[FEATURE] \'',
              'labels: [\'enhancement\']',
              'assignees: \'\'',
              '---',
              '',
              '## Проблема',
              '',
              'Краткое описание проблемы, которую вы хотите решить. Например: Я всегда расстраиваюсь когда [...]',
              '',
              '## Предлагаемое решение',
              '',
              'Краткое описание того, что вы хотите произойти.',
              '',
              '## Альтернативы',
              '',
              'Краткое описание любых альтернативных решений или функций, которые вы рассматривали.',
              '',
              '## Дополнительная информация',
              '',
              'Добавьте любую другую информацию или скриншоты о запросе функции здесь.'
            ].join('\n');

            const templates = [
              { name: 'bug_report.md', content: bugReportTemplate },
              { name: 'feature_request.md', content: featureRequestTemplate }
            ];

            for (const template of templates) {
              try {
                await github.rest.repos.createOrUpdateFileContents({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  path: `.github/ISSUE_TEMPLATE/${template.name}`,
                  message: `Add ${template.name} template`,
                  content: Buffer.from(template.content).toString('base64'),
                  branch: 'main'
                });
                
                console.log(`✅ ${template.name} template created`);
              } catch (error) {
                console.log(`❌ Failed to create ${template.name} template:`, error.message);
              }
            } 